// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.ut.beans;

import ee.ut.beans.PurchaseOrderBean;

privileged aspect PurchaseOrderBean_Roo_JavaBean {
    
    public Long PurchaseOrderBean.getSelectedId() {
        return this.selectedId;
    }
    
    public void PurchaseOrderBean.setSelectedId(Long selectedId) {
        this.selectedId = selectedId;
    }
    
}
