package ee.ut.domain;


public enum POstatus {

	 PENDING_CONFIRMATION, PENDING_UPDATE, UPDATE_REJECTED, OPEN, RECIEVED, REJECTED, CLOSED, CANCELLATION_REQUESTED, DISPATCHED, DELIVERED, REJECTED_BY_CUSTOMER, RETURNED, INVOICED;

   
}
